export const cropGuides = [
  {
    id: "tomato",
    name: "Tomatoes",
    description: "Guide to growing healthy, high-yielding tomato plants",
    category: "vegetables",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Spring to Fall",
    soilPH: "6.0 - 6.8",
    fertilizerNeeds: "High in phosphorus and potassium",
  },
  {
    id: "corn",
    name: "Corn",
    description: "Tips for successful corn cultivation and maximizing yields",
    category: "grains",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Late Spring to Summer",
    soilPH: "5.8 - 7.0",
    fertilizerNeeds: "High in nitrogen",
  },
  {
    id: "strawberry",
    name: "Strawberries",
    description: "Complete guide to growing sweet, juicy strawberries",
    category: "fruits",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Spring to Early Summer",
    soilPH: "5.5 - 6.5",
    fertilizerNeeds: "Balanced NPK with micronutrients",
  },
  {
    id: "lettuce",
    name: "Lettuce",
    description: "How to grow crisp, flavorful lettuce varieties",
    category: "vegetables",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Spring and Fall",
    soilPH: "6.0 - 7.0",
    fertilizerNeeds: "Moderate nitrogen, low phosphorus",
  },
  {
    id: "wheat",
    name: "Wheat",
    description: "Commercial wheat production guide for maximum yield",
    category: "grains",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Fall to Early Summer (Winter Wheat)",
    soilPH: "6.0 - 7.0",
    fertilizerNeeds: "Nitrogen-focused with phosphorus",
  },
  {
    id: "blueberry",
    name: "Blueberries",
    description: "Growing guide for productive blueberry bushes",
    category: "fruits",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Spring to Summer",
    soilPH: "4.5 - 5.5 (Acidic)",
    fertilizerNeeds: "Acid-loving plant fertilizer",
  },
  {
    id: "potato",
    name: "Potatoes",
    description: "From planting to harvest: complete potato growing guide",
    category: "vegetables",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Spring to Fall",
    soilPH: "5.8 - 6.5",
    fertilizerNeeds: "Balanced NPK, higher in phosphorus and potassium",
  },
  {
    id: "rice",
    name: "Rice",
    description: "Commercial rice cultivation techniques and best practices",
    category: "grains",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Spring to Fall",
    soilPH: "5.5 - 6.5",
    fertilizerNeeds: "High nitrogen, moderate phosphorus and potassium",
  },
  {
    id: "apple",
    name: "Apples",
    description: "Orchard management guide for apple trees",
    category: "fruits",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Spring to Fall (Perennial)",
    soilPH: "6.0 - 7.0",
    fertilizerNeeds: "Balanced NPK with calcium",
  },
  {
    id: "lavender",
    name: "Lavender",
    description: "Growing fragrant lavender for essential oil production",
    category: "specialty",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Spring to Summer",
    soilPH: "6.5 - 7.5",
    fertilizerNeeds: "Low nitrogen, well-draining soil",
  },
  {
    id: "coffee",
    name: "Coffee",
    description: "Sustainable coffee cultivation practices",
    category: "specialty",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Year-round (Tropical)",
    soilPH: "6.0 - 6.5",
    fertilizerNeeds: "Balanced with micronutrients",
  },
  {
    id: "saffron",
    name: "Saffron",
    description: "Guide to growing and harvesting valuable saffron crocus",
    category: "specialty",
    image: "/placeholder.svg?height=400&width=600",
    growingSeason: "Fall Flowering",
    soilPH: "6.0 - 8.0",
    fertilizerNeeds: "Low to moderate, well-draining soil",
  },
]
