export const dealers = [
  {
    id: "1",
    name: "Green Valley Farm Supply",
    type: "Distributor",
    address: "123 Farm Road",
    city: "Greenville",
    state: "CA",
    zip: "95945",
    phone: "(530) 555-1234",
    email: "info@greenvalleysupply.com",
    website: "https://example.com/greenvalley",
    region: "north",
  },
  {
    id: "2",
    name: "Southern Ag Solutions",
    type: "Retailer",
    address: "456 Main Street",
    city: "Southport",
    state: "FL",
    zip: "32409",
    phone: "(850) 555-5678",
    email: "sales@southernagsolutions.com",
    website: "https://example.com/southernag",
    region: "south",
  },
  {
    id: "3",
    name: "Eastern Fertilizer Co.",
    type: "Distributor",
    address: "789 Commerce Blvd",
    city: "Eastville",
    state: "NC",
    zip: "27890",
    phone: "(919) 555-9012",
    email: "contact@easternfertilizer.com",
    website: "https://example.com/eastern",
    region: "east",
  },
  {
    id: "4",
    name: "Western Growers Supply",
    type: "Wholesaler",
    address: "321 Harvest Lane",
    city: "Westfield",
    state: "CA",
    zip: "93274",
    phone: "(559) 555-3456",
    email: "info@westerngrowers.com",
    website: "https://example.com/western",
    region: "west",
  },
  {
    id: "5",
    name: "Central Farm Services",
    type: "Retailer",
    address: "654 Agricultural Way",
    city: "Centerville",
    state: "IA",
    zip: "52544",
    phone: "(641) 555-7890",
    email: "service@centralfarm.com",
    website: "https://example.com/central",
    region: "central",
  },
  {
    id: "6",
    name: "Northland Agricultural Supply",
    type: "Distributor",
    address: "987 Crop Circle",
    city: "Northfield",
    state: "MN",
    zip: "55057",
    phone: "(507) 555-2345",
    email: "sales@northlandag.com",
    website: null,
    region: "north",
  },
  {
    id: "7",
    name: "South County Farm Store",
    type: "Retailer",
    address: "246 Rural Route",
    city: "Southfield",
    state: "GA",
    zip: "30213",
    phone: "(770) 555-6789",
    email: "info@southcountyfarm.com",
    website: "https://example.com/southcounty",
    region: "south",
  },
  {
    id: "8",
    name: "East Coast Agronomy",
    type: "Consultant",
    address: "135 Soil Street",
    city: "Eastport",
    state: "ME",
    zip: "04631",
    phone: "(207) 555-0123",
    email: "consult@eastcoastagronomy.com",
    website: "https://example.com/eastcoast",
    region: "east",
  },
  {
    id: "9",
    name: "West Valley Fertilizers",
    type: "Manufacturer",
    address: "864 Production Parkway",
    city: "Westlake",
    state: "OR",
    zip: "97068",
    phone: "(503) 555-4567",
    email: "orders@westvalleyfert.com",
    website: "https://example.com/westvalley",
    region: "west",
  },
  {
    id: "10",
    name: "Midland Crop Services",
    type: "Distributor",
    address: "753 Center Avenue",
    city: "Midway",
    state: "KS",
    zip: "67063",
    phone: "(785) 555-8901",
    email: "service@midlandcrop.com",
    website: "https://example.com/midland",
    region: "central",
  },
]
